name: Get latest commit hash
description: Get hash of the latest commit in specific repo
inputs:
    url:
        description: Target repo
        required: true
        default: 'https://github.com/xkinput/KeyTao.git'
    branch:
        description: Target branch
        required: false
        default: master

runs:
    using: composite
    steps:
        - id: my-step
          run: |
            result=$(git ls-remote ${{ inputs.url }} ${{ inputs.branch }})
            echo "hash=${result%%$'\t'*}" >> $GITHUB_OUTPUT
          shell: bash

outputs:
    hash:
        value: ${{ steps.my-step.outputs.hash }}