name: Update Release Info on Cloudflare Pages

on:
  release:
    types: [published, edited]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Generate release page
        run: |
          mkdir -p ./upload
          cat << EOF > ./upload/xxxk.html
          <!DOCTYPE html>
          <html lang="zh-CN">
          <head>
              <meta charset="UTF-8">
              <title>小小星空最新发布信息</title>
          </head>
          <body>
              <h1 .release_tag_name>${{ github.event.release.tag_name }}</h1>
              <p>【名称】<span .release_name>${{ github.event.release.name }}</span></p>
              <p>【预发布版本】<span .release_prerelease>${{ github.event.release.prerelease }}</span></p>
              <p>【发布时间】<span .release_published_at>${{ github.event.release.published_at }}</span></p>
              <p>【内容说明】</p>
              <pre .release_body>${{ github.event.release.body }}</pre>
          </body>
          </html>
          EOF

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./upload/ --project-name=latest-release
