name: Build Releases JSON

on:
  release:
    types: [published, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch GitHub Releases
        run: |
          set -e
          mkdir -p jsons

          curl -s \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/xkinput/xxxk/releases" \
            > jsons/xxxk.json

          curl -s \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/xkinput/windikt/releases" \
            > jsons/windikt.json

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy jsons --project-name=github-releases --branch=main
