name: Get the hash of the lastest commit in KeyTao
on:
    workflow_dispatch
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - id: my-caller-step
              uses: ./.github/actions/get-latest-commit-hash
              with:
                url: 'https://github.com/xkinput/KeyTao.git'
                branch: master
            - run: echo "${{ steps.my-caller-step.outputs.return }}"